In [8]:
import os
from glob import glob
import pandas as pd

In [49]:
base_path = '../../../../../Downloads/HAM10000'
images_path = f"{base_path}/HAM10000_images"

metadata = pd.read_csv(f'{base_path}/HAM10000_metadata.csv')
metadata

images_path_crop = '../../../../../Downloads/HAM10000_BOUNDING_BOX_CROP'

In [50]:
metadata[metadata['dx'] == 'nv']

        lesion_id      image_id  dx    dx_type   age     sex     localization
64    HAM_0001751  ISIC_0024698  nv  consensus  70.0    male             face
1210  HAM_0000559  ISIC_0024693  nv  follow_up  45.0  female  upper extremity
2976  HAM_0004932  ISIC_0032212  nv  follow_up  45.0  female             foot
2977  HAM_0004516  ISIC_0025775  nv  follow_up  45.0  female             neck
2978  HAM_0006510  ISIC_0029828  nv  follow_up  55.0  female  lower extremity
...           ...           ...  ..        ...   ...     ...              ...
9682  HAM_0006283  ISIC_0027924  nv  consensus  20.0    male            chest
9683  HAM_0000102  ISIC_0031547  nv  consensus  20.0    male             back
9684  HAM_0000102  ISIC_0032221  nv  consensus  20.0    male             back
9685  HAM_0005314  ISIC_0030693  nv  consensus  40.0    male             neck
9686  HAM_0003322  ISIC_0031649  nv  consensus  50.0  female             face

[6705 rows x 7 columns]

In [51]:
images = sorted(glob(os.path.join(images_path_crop,"*jpg")))
len(images)

7818

In [52]:
metadata = metadata[['lesion_id', 'image_id', 'dx']]
mask = (metadata['dx'] == 'mel') | (metadata['dx'] == 'nv')
metadata = metadata[mask]
metadata

         lesion_id      image_id   dx
64     HAM_0001751  ISIC_0024698   nv
1210   HAM_0000559  ISIC_0024693   nv
1211   HAM_0000871  ISIC_0025964  mel
1212   HAM_0000871  ISIC_0030623  mel
1213   HAM_0000040  ISIC_0027190  mel
...            ...           ...  ...
9683   HAM_0000102  ISIC_0031547   nv
9684   HAM_0000102  ISIC_0032221   nv
9685   HAM_0005314  ISIC_0030693   nv
9686   HAM_0003322  ISIC_0031649   nv
10014  HAM_0003521  ISIC_0032258  mel

[7818 rows x 3 columns]

In [53]:
def get_classification(dx):
    if dx == 'mel':
        return 'Malignant'
    return 'Benignant'

In [54]:
# Crear paths
for index, row in metadata.iterrows():
    full_path = f'{images_path_crop}/{row['image_id']}.jpg'
    metadata.at[index, 'path'] = full_path
    metadata.at[index, 'classification'] = get_classification(row['dx'])

In [55]:
metadata.to_csv('../data/02_dataset_crop.csv', index=False)